services:
  postgres:
    image: postgres:16-alpine
    container_name: marqetplace-container
    environment:
      POSTGRES_USER: marqetplace
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: marqetplace_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

